name: git-reader_demo
on:
  push:
    branches: [main]
jobs:
  git-reader:
    env:
      GHPAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout:git-reader
      uses: actions/checkout@v3
    - name: git-reader:do-work
      run: |
          export START=$(cat ./inputs.json| jq -r '.start')
          export END=$(cat ./inputs.json| jq -r '.end')
          export REPO=$(cat ./inputs.json| jq -r '.repo')
          export ORG=$(cat ./inputs.json| jq -r '.org')
          export GHPAT=${{ env.GHPAT }}
          chmod +x ./git-reader.sh; ./git-reader.sh
