name: git-reader_demo
on:
  push:
    branches: [none]
jobs:
  git-reader:
    env:
      GHPAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: do-work
      run: |
          export START="$(cat inputs.json| jq -r '.start')"
          export END="$(cat inputs.json| jq -r '.end')"
          export REPO="$(cat inputs.json| jq -r '.repo')"
          export ORG="$(cat inputs.json| jq -r '.org')"
          chmod +x ./git-reader.sh; ./git-reader.sh
